name: Build static site for deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.4"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy to deploy branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git branch -D deploy || true
          git checkout --orphan deploy

          shopt -s extglob
          rm -rf !(.git|dist)
          shopt -u extglob

          mv dist/* .

          git add .
          git commit -m "Deploy from main: $(date)"
          git push --force origin deploy
